/*
 * Copyright (C) 2014 Christoffer T. Timm
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.cordovastudio.branding.artwork;

import org.cordovastudio.utils.ImageUtils;

import java.awt.*;

public class Artwork {

    private static Image loadArtwork(String imageFileName) {
        return ImageUtils.loadArtwork(imageFileName);
    }

    public static class Shadows {
        // Shadow graphics. This was generated by creating a drop shadow in
        // Gimp, using the parameters x offset=10, y offset=10, blur radius=10,
        // (for the small drop shadows x offset=10, y offset=10, blur radius=10)
        // color=black, and opacity=51. These values attempt to make a shadow
        // that is legible both for dark and light themes, on top of the
        // canvas background (rgb(150,150,150). Darker shadows would tend to
        // blend into the foreground for a dark holo screen, and lighter shadows
        // would be hard to spot on the canvas background. If you make adjustments,
        // make sure to check the shadow with both dark and light themes.
        //
        // After making the graphics, I cut out the top right, bottom left
        // and bottom right corners as 20x20 images, and these are reproduced by
        // painting them in the corresponding places in the target graphics context.
        // I then grabbed a single horizontal gradient line from the middle of the
        // right edge,and a single vertical gradient line from the bottom. These
        // are then painted scaled/stretched in the target to fill the gaps between
        // the three corner images.
        //
        // Filenames: bl=bottom left, b=bottom, br=bottom right, r=right, tr=top right

        // Normal Drop Shaow
        public static final Image ShadowBottom          = loadArtwork("shadows/shadow-b.png");
        public static final Image ShadowBottomLeft      = loadArtwork("shadows/shadow-bl.png");
        public static final Image ShadowBottomRight     = loadArtwork("shadows/shadow-br.png");
        public static final Image ShadowRight           = loadArtwork("shadows/shadow-r.png");
        public static final Image ShadowTopRight        = loadArtwork("shadows/shadow-tr.png");

        // Small Drop Shadow
        public static final Image Shadow2Bottom         = loadArtwork("shadows/shadow2-b.png");
        public static final Image Shadow2BottomLeft     = loadArtwork("shadows/shadow2-bl.png");
        public static final Image Shadow2BottomRight    = loadArtwork("shadows/shadow2-br.png");
        public static final Image Shadow2Right          = loadArtwork("shadows/shadow2-r.png");
        public static final Image Shadow2TopRight       = loadArtwork("shadows/shadow2-tr.png");
    }

}
